--- 
after_success: 
  - "npm run report-coverage"
  - "npm publish"
before_install: 
  - "npm i -g nmp@^1.0.0"
before_script: 
  - "npm prune"
cache: 
  directories: 
    - node_modules
language: node_js
node_js: 
  - iojs
notifications: 
  email: false
script: 
  - "npm run check-coverage"
  - "npm run cover"
  - "npm run build"
sudo: false
